### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by santhoshvai**
* Bumped version numbers
* Tools attribute usage improved
* SwipeRefreshLayout color scheme usage improved

### CODE REVIEW

**Comment by JoseAlcerreca** [comment]
Do test pass? We need CI on this project.

**Comment by santhoshvai** [comment]
The tests pass, when animations are turned off. Yes, a CI here would be great. I can test a valid travis config when I find time.

**Comment by JoseAlcerreca** [comment]
Some changes done in https://github.com/googlecodelabs/android-testing/commit/9327df98938bf6e0a60402b36ada89a46a689327 
feel free to pull and resend. Thanks!

**Comment by santhoshvai** [comment]
Thanks @JoseAlcerreca Will do ASAP.

**Pull request closed without merging**
